name: Winatbookkeeping.com
favicon: null
layout_spectrum: 0.2907819878309965
typography_spectrum: 0.8696626487653702
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.039409904507920146
  lightness: 0.5886977296322584
  saturation: 0.9848456711042672
  rhythmicContrast: 0.6966802473179996
purpose: []
